version: "3.7"


services:
  event_db:
    build: ./mysql
    container_name: event_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${EVENT_DB_PWD}
    ports:
      - "3307:3306"
    networks:
      - db_nw


  flask:
    build: ./flask
    container_name: flask
    restart: always
    depends_on:
      - event_db
    environment:
      - EVENT_DB_HOST=event_db
      - EVENT_DB_PWD=${EVENT_DB_PWD}
      - EVENT_DB_PORT=3306
    networks:
      - web_nw
      - db_nw

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - flask
    restart: always
    ports:
      - "80:80"
    networks:
      - web_nw

  scrapy:
    build: ./scrapy
    container_name: scrapy
    restart: always
    depends_on:
      - event_db
      - selenium
    environment:
      - EVENT_DB_HOST=event_db
      - EVENT_DB_PWD=${EVENT_DB_PWD}
      - EVENT_DB_PORT=3306
    networks:
      - db_nw
      - scrape_nw
    
  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    restart: always
    expose: 
      - "4444"
    volumes:
      - /dev/shm:/dev/shm
    networks: 
      - scrape_nw
    ports: 
      - "4444:4444"
    
networks:
  db_nw:
    driver: bridge
  web_nw:
    driver: bridge
  scrape_nw:
    driver: bridge
